name: Greeting from Mona

on: push


jobs:
  environment: curso_devops
  my-job:
    name: My Job
    runs-on: ubuntu-latest
    steps:
      - name: Print a greeting
        env:
          MY_VAR: Hi there! My name is
          FIRST_NAME: Mona
          MIDDLE_NAME: The
          LAST_NAME: Octocat
        run: |
          echo $MY_VAR $FIRST_NAME $MIDDLE_NAME $LAST_NAME.
#name: SonarCloud analysis
#on:
  # Trigger analysis when pushing in master or pull requests, and when creating
  # a pull request.
 # push:
  #  branches:
   #   - main
 # pull_request:
  #  types:
   #   - opened

 # environment: curso_devops
  
  #env:
   # ALUMNO: ${{ vars.ALUMNO }}
    #EMAIL: ${{ vars.EMAIL }}
   # RAMA: $github.ref_name
   # URL: ${{ secrets.URL }}

  #steps:
    #- uses: actions/checkout@v3
   # - name: "Say Hello Mona it's Monday"
    #  run: echo "Holaaa"
    #- name: Uso variables
     # - if: $RAMA == 'dev'
      #  run: echo "VARIABLE -> $ALUMNO / RAMA -> $RAMA"
      #- if: $RAMA == 'qa'
       # run: echo "VARIABLE -> $EMAIL / RAMA -> $RAMA"
      #- if: $RAMA == 'main'
       # run: echo "VARIABLES -> $ALUMNO & $EMAIL / RAMA -> $RAMA"
            
    #- name: Uso de secreto
     # run: |
      #    echo "RAMA -> $RAMA"
       #   consulta=$(curl -s "$URL")
        #  echo "$consulta"