name: Greeting from Mona

on: push


jobs:
  job1:
    environment: curso_devops
    name: My Job
    runs-on: ubuntu-latest
    steps:
      - name: Print a greeting
        env:
          MY_VAR: Hi there! My name is
          FIRST_NAME: Mona
          MIDDLE_NAME: The
          LAST_NAME: Octocat
        run: |
          echo $MY_VAR $FIRST_NAME $MIDDLE_NAME $LAST_NAME.

  job2:
    environment: curso_devops
    name: My Job
    runs-on: ubuntu-latest
    steps:
      - name: Uso variables
        env:
          ALUMNO: ${{ vars.ALUMNO }}
          EMAIL: ${{ vars.EMAIL }}
          RAMA: ${{GITHUB_REF_NAME}}
          URL: ${{ secrets.URL }}
        run: |
          echo "$RAMA"

    #steps:
      
      #- uses: actions/checkout@v3
        
     #   - if: $GITHUB_REF_NAME == 'dev'
          #run: echo "VARIABLE -> $ALUMNO / RAMA -> $GITHUB_REF_NAME"
      #  - if: $GITHUB_REF_NAME == 'qa'
         # run: echo "VARIABLE -> $EMAIL / RAMA -> $GITHUB_REF_NAME"
       # - if: $GITHUB_REF_NAME == 'main'
        #  run: echo "VARIABLES -> $ALUMNO & $EMAIL / RAMA -> $GITHUB_REF_NAME"
#name: SonarCloud analysis
#on:
  # Trigger analysis when pushing in master or pull requests, and when creating
  # a pull request.
 # push:
  #  branches:
   #   - main
 # pull_request:
  #  types:
   #   - opened

 # environment: curso_devops
  
  #env:
   # ALUMNO: ${{ vars.ALUMNO }}
    #EMAIL: ${{ vars.EMAIL }}
   # RAMA: $github.ref_name
   # URL: ${{ secrets.URL }}

  #steps:
    #- uses: actions/checkout@v3
    
    #- name: Uso variables
     # - if: $RAMA == 'dev'
      #  run: echo "VARIABLE -> $ALUMNO / RAMA -> $RAMA"
      #- if: $RAMA == 'qa'
       # run: echo "VARIABLE -> $EMAIL / RAMA -> $RAMA"
      #- if: $RAMA == 'main'
       # run: echo "VARIABLES -> $ALUMNO & $EMAIL / RAMA -> $RAMA"
            
    #- name: Uso de secreto
     # run: |
      #    echo "RAMA -> $RAMA"
       #   consulta=$(curl -s "$URL")
        #  echo "$consulta"