name: SonarCloud analysis
on:
  # Trigger analysis when pushing in master or pull requests, and when creating
  # a pull request.
  push:
    branches:
      - main
  pull_request:
    types:
      - opened

  environment: curso_devops
  
  #env:
   # ALUMNO: ${{ vars.ALUMNO }}
    #EMAIL: ${{ vars.EMAIL }}
   # RAMA: $github.ref_name
   # URL: ${{ secrets.URL }}

  steps:
    #- uses: actions/checkout@v3
    - name: "Say Hello Mona it's Monday"
      run: echo "Holaaa"
    #- name: Uso variables
     # - if: $RAMA == 'dev'
      #  run: echo "VARIABLE -> $ALUMNO / RAMA -> $RAMA"
      #- if: $RAMA == 'qa'
       # run: echo "VARIABLE -> $EMAIL / RAMA -> $RAMA"
      #- if: $RAMA == 'main'
       # run: echo "VARIABLES -> $ALUMNO & $EMAIL / RAMA -> $RAMA"
            
    #- name: Uso de secreto
     # run: |
      #    echo "RAMA -> $RAMA"
       #   consulta=$(curl -s "$URL")
        #  echo "$consulta"