name: Muestra Var & Secr
on:
  # Trigger analysis when pushing in master or pull requests, and when creating
  # a pull request.
  push:
    branches:
      - main
  pull_request:
      types: [opened, synchronize, reopened]

jobs:
  runs-on: ubuntu-latest

  environment: curso_devops
  
  env:
    ALUMNO: ${{ vars.ALUMNO }}
    EMAIL: ${{ vars.EMAIL }}
    RAMA: $github.ref_name
    URL: ${{ secrets.URL }}

  steps:
    #- uses: actions/checkout@v3

    - name: Uso variables
      - if: $RAMA == 'dev'
        run: echo "VARIABLE -> $ALUMNO / RAMA -> $RAMA"
      - if: $RAMA == 'qa'
        run: echo "VARIABLE -> $EMAIL / RAMA -> $RAMA"
      - if: $RAMA == 'main'
        run: echo "VARIABLES -> $ALUMNO & $EMAIL / RAMA -> $RAMA"
            
    #- name: Uso de secreto
     # run: |
      #    echo "RAMA -> $RAMA"
       #   consulta=$(curl -s "$URL")
        #  echo "$consulta"